version: "3.7"
services:
  app:
    build:
      args:
        user: arsh
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: news_aggregator
    container_name: news-aggregator-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - news_aggregator_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
  db:
    image: mysql:8.0
    container_name: news_aggregator-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - news_aggregator_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: news-aggregator-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 100M
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - news_aggregator_network
  nginx:
    image: nginx:alpine
    container_name: news-aggregator-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - news_aggregator_network
networks:
  news_aggregator_network:
    driver: bridge
volumes:
  dbdata:
    driver: local